イベントのバナーをコンポネントに移し、期限が切れると隠れるようにした
ut-code/website pull request #95
Opened 2024-01-07 16:23 UTC by aster-void

- shortens GlobalHeader.tsx
- allow auto expire (unsure)

デプロイのサービスのビルドの仕組みを知らないので、後半はもしかしたら動かないかもです

2024-01-11 02:41 UTC, chelproc requested changes
Gatsbyは静的サイトジェネレーターとして使ってるので `new Date` はビルド時の日付になっちゃいますね
でクライアント再度のReactが読み込まれたタイミングで消えるのでまずいです

コンポーネント化は中途半端にやるくらいならやらないほうがマシかなという感じです

2024-01-11 03:18 UTC, aster-void commented
> Gatsbyは静的サイトジェネレーターとして使ってるので `new Date` はビルド時の日付になっちゃいますね
> でクライアント再度のReactが読み込まれたタイミングで消えるのでまずいです

そんな感じはしてました...消し忘れの問題どうにかならないですかね？

2024-01-11 05:01 UTC, chelproc commented
バナーを作るときに消すPRも同時に作って、そのPRを[適当なボット](https://mergify.com/)にマージさせるのが一番いいと思いますね

2024-01-12 15:41 UTC, aster-void commented
bot の使い方は分からないですが、これなら消すハードルが下がるので忘れにくくなると思います。

2024-01-13 00:25 UTC, chvmvd reviewed
コメントアウトの方が普通にはやくないですかね？
別に、ボットを作らなくてもリマインドして、手動でマージでも運用は全然可能ですし。

2024-01-13 14:50 UTC, aster-void commented
> コメントアウトの方が普通にはやくないですかね？この場合、引数の意味を実装から読み解く方が手間になる気がしますね。 別に、ボットを作らなくてもリマインドして、手動でマージでも運用は全然可能ですし。

インタフェースは実装から読み解くよりも変数名から推測する使い方を想定していますが、実装から読み解いてもそこまで複雑ではないので、思想の違いで消されたコードをログからコピペしてくるよりは手間でないと思います。

2024-01-13 15:41 UTC, chvmvd commented
> > コメントアウトの方が普通にはやくないですかね？この場合、引数の意味を実装から読み解く方が手間になる気がしますね。 別に、ボットを作らなくてもリマインドして、手動でマージでも運用は全然可能ですし。
> 
> 
> 
> インタフェースは実装から読み解くよりも変数名から推測する使い方を想定していますが、実装から読み解いてもそこまで複雑ではないので、思想の違いで消されたコードをログからコピペしてくるよりは手間でないと思います。

このような場合、コンポーネント側で表示するかを決めるのはあまり一般的ではなく引数名から読み解くのが難しそうという気がしますね。(コンポーネント側の責務ではない)
そもそも、コードを削除するということ自体があまり適切ではないというのは思想云々ではない気がします。

2024-01-15 01:57 UTC, chelproc commented
自分も↑に賛成です。
コンポーネントツリーの中で表示・非表示を切り替えるのが親と子どちらの責務かという話だと思うのですが、表示・非表示の状態に関わらず、少なくとも親コンポーネントが子コンポーネントを使っている以上、親コンポーネントが「自分が子コンポーネントを表示している」という知識を持つことは避けられません。であれば表示/非表示も親が担うのが自然だという認識です（アニメーションが欲しいとかになるとどうしようもなくなるのですが）。

2024-01-15 01:59 UTC, chelproc commented
あとは最初に「中途半端に」と書いたのは、GlobalHeaderコンポーネントの中で、他で使われていないにも関わらず、EventBannerだけをサブツリーに移し、他の部分は普通にベタ書きされていることを指摘していました。

2024-01-17 15:17 UTC, aster-void commented
じゃあコメントアウトのままにしますか...

2024-01-17 15:17 UTC, closed without merging