import のエイリアスを可能にした
ut-code/website pull request #98
Opened 2024-01-10 17:46 UTC by aster-void

- gatsby settings
  - [install] gatsby-plugin-alias-imports (50k install / 5k weekly)
  - [edit] added some aliases to gatsby-config.js

- eslint settings
  - [install] eslint-import-resolver-alias (250k weekly install)
  - [edit] added alias resolver to eslintrc.js

- (seemingly) unrelated package updates
  - update react-icons to 5.0.0 because it suddenly started to generate eslint warnings 
      (refer https://github.com/react-icons/react-icons/issues/509 )

2024-01-10 18:25 UTC, aster-void commented
tsc は知らないのでやってないです。時間があったら明日やります

2024-01-11 02:47 UTC, chelproc requested changes
5k/週のライブラリは正直使わないほうがいいと思います
特に npm はパッケージインストール時に任意のプログラムを実行できたりするのでもっと慎重になったほうがいいです。
GitHub のリポジトリもアーカイブされています。メンテ状況とかもちゃんとチェックしたほうがいいですね。
https://github.com/rowanfreeman/gatsby-plugin-alias-imports 

基本的にサークルのプロジェクトはメンテコストを可能な限り低く抑えるのが大事です。import 文のわずかな読みやすさと引き換えにプロジェクト構成の複雑化を取るかと言われるとサークルのプロジェクトとしてはナシかなという感じです。

技術的な点を言うと、TypeScript側の設定もしないと型チェックやエディタ支援が動かなくなると思います

2024-01-11 03:52 UTC, aster-void commented
https://www.gatsbyjs.com/docs/how-to/custom-configuration/add-custom-webpack-config/#absolute-imports
プラグインなしでもできそうですが、こっちならいいですかね？
TypeScript の config は明日書きます。

2024-01-11 05:04 UTC, chelproc commented
正直 Webpack、ESLint、TypeScriptの3つの設定を弄って頑張って同期を取ってまでこの機能を入れるメリットが見当たらないと思っています。
VSCodeでimport文は自動生成できますし、ファイルを移動したときは自動で書き換えられますし、そもそもimport文を上から読んでいくことはなくないですかね？

2024-01-11 05:47 UTC, aster-void commented
> 正直 Webpack、ESLint、TypeScriptの3つの設定を弄って頑張って同期を取ってまでこの機能を入れるメリットが見当たらないと思っています。
> VSCodeでimport文は自動生成できますし、ファイルを移動したときは自動で書き換えられますし、そもそもimport文を上から読んでいくことはなくないですかね？

確かに。じゃあいいか

2024-01-11 05:47 UTC, closed without merging